name = "quotes-api"
main = "src/index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "QUOTES_KV", id = "5f991880e8fd4eb9a0456fd85e22c347", preview_id = "e7a543eea9dc4387921ec4794cd9645d" }
]